### PR TITLE
Olga: adding jetty support for Waitrest

### PR DESCRIPTION
**Pull request by olyabobra**
We want to be able to start waitrest with embedded Jetty server (the Sun one doesn't seem to be performing well enough).

### CODE REVIEW

**Comment by danielbodart** [comment]
Hey Olga,

Would you mind making a few changes to the pull request?

Basically there are some much nicer ways to start the application:
- Delete the port and serverClass methods
- Take the commandline arguments and create an in memory Properties object
- Create a ServerConfiguration from the properties
- Use ApplicationBuilder.start to create you server 

If you do this should support all RestServer implementations plus it will get rid of a bunch of exceptions, null checks etc.

Dan

**Comment by olyabobra** [comment]
Cool, I'll give it a go! Thanks!

**Comment by danielbodart** [comment]
Actually the Properties part is probably optional, which ever keeps the code as simple as possible!

**Comment by olyabobra** [comment]
Hello Dan,

how is this looking? I used Properties; worked nicer with them.

Thanks, Olga

**Comment by danielbodart** [comment]
This is looking good but a couple of quick things: 

 # I think the Waitrest class should take a properties object not the serverconfig as it doesn't expose the dependency on utterlyidle (they are embedded)
 # convert basepath to properties as well
 # the default constructor can then just pass an empty properties and all the defaults will come from utterlyidle

Make sense?

**Comment by olyabobra** [comment]
It does :) How about now? Thanks for reviewing!

**Comment by olyabobra** [comment]
Made the commit with Restaurant created by applicationBuilder

**Comment by olyabobra** [comment]
I know what you mean about the duplication. I've made some changes but not sure they are improving things; what do you reckon? Thanks!

**Comment by danielbodart** [comment]
This looks good, though I think you can get rid of the exception block in the WaitRest contrustructor as I don't think there is anything that throws now?

**Comment by olyabobra** [comment]
You are right! Done

**Comment by danielbodart** [comment]
Good work, I know I've already merged but I just noticed one more thing!

I don't think we need a dependency on Jetty any more? As it works with any Server implementation. Would you mind trying?

**Comment by olyabobra** [comment]
Sure, I'll make the change tomorrow. You are absolutely right, we don't
need those dependencies now.

**Pull request merged**
